# SPDX-FileCopyrightText: Copyright (c) 2019-2025 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
AllCops:
  NewCops: enable
  DisplayCopNames: true
  TargetRubyVersion: 2.3
  SuggestExtensions: false
Minitest/EmptyLineBeforeAssertionMethods:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/MultilineMethodCallIndentation:
  Enabled: false
Metrics/AbcSize:
  Max: 50
Metrics/MethodLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/ParameterLists:
  Max: 10
Layout/ParameterAlignment:
  Enabled: false
Lint/ShadowedException:
  Enabled: false
plugins:
  - rubocop-rake
  - rubocop-minitest
  - rubocop-performance
require: []
